### ISSUE TITLE
Open Iconic prefix "oi-" missing

### ISSUE THREAD

**Issue by opus-2** [idleberg/vscode-svg-icons#2]
When typing `oi-` it doesn't suggest a proper list of classes, as it would with the other prefixes (`octicon-`, `bi-` , etc.). Upon checking the source, I've noticed the files html/oi.json and jsx/oi.json don't  have the correct prefix specified. Example:

>  "oi-account-login": {
>     "body": "<svg class=\"icon\">\n\t<use xlink:href=\"${1:open-iconic.svg}#account-login\" class=\"account-login\"></use>\n</svg>",
>     "description": "<use>",
>     **"prefix": "account-login"**  <-- shouldn't this be "oi-account-login" ?
>   },

**Comment by idleberg** [comment]
Thanks for reporting, fixed this in v0.6.5
